apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "test-devops.fullname" . }}-app
  labels:
    app: {{ include "test-devops.name" . }}
    component: app
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "test-devops.name" . }}
      component: app
  template:
    metadata:
      labels:
        app: {{ include "test-devops.name" . }}
        component: app
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NODE_ENV
              value: {{ .Values.app.env.NODE_ENV | quote }}
            - name: STATSD_HOST
              value: {{ .Values.app.env.STATSD_HOST | quote }}
            - name: STATSD_PORT
              value: {{ .Values.app.env.STATSD_PORT | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          # readiness/liveness probe เพิ่มได้ตามจริงของ app
