{{- if .Values.graphite.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: graphite
  labels:
    app: graphite
spec:
  type: {{ .Values.graphite.serviceType }}
  selector:
    app: graphite
  ports:
    - name: web
      port: {{ .Values.graphite.webPort }}
      targetPort: {{ .Values.graphite.webPort }}
      {{- if eq .Values.graphite.serviceType "NodePort" }}
      nodePort: {{ .Values.graphite.nodePort }}
      {{- end }}
    - name: statsd
      port: 8125
      targetPort: 8125
      protocol: UDP
    - name: statsd-admin
      port: 8126
      targetPort: 8126
{{- end }}
