apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-devops-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/<YOUR_GITHUB_ACCOUNT>/test-devops.git'
    targetRevision: main
    path: k8s/helm/app-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: test-devops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
