name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - "Dockerfile"
      - "index.js"
      - "package.json"
      - ".github/workflows/build-and-push.yml"

env:
  REGION: asia-southeast1
  REPOSITORY: test-devops-images
  IMAGE_NAME: app

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      - name: Build Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t $REGION-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/$REPOSITORY/$IMAGE_NAME:$IMAGE_TAG .

      - name: Trivy scan image
        uses: aquasecurity/trivy-action@v0.33.1
        with:
          scan-type: 'image'
          image-ref: '$REGION-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/$REPOSITORY/$IMAGE_NAME:${{ github.sha }}'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'
          format: 'table'

      - name: Push Docker image
        if: success()
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker push $REGION-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/$REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
