name: DAST - OWASP ZAP

on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 * * *"  # ปรับเวลาตามต้องการ (UTC)

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          target: ${{ secrets.DAST_TARGET_URL }}
          cmd_options: >
            -a
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
